- alias: Harmony on
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: media_player.cctv
      from: 'off'
  action:
    - service: remote.turn_on
      entity_id: remote.living_room
      data:
        activity: 25766446


- alias: Harmony off
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: media_player.cctv
      to: 'off'
      for:
        seconds: 30
  action:
    - service: remote.turn_off
      entity_id: remote.living_room

- alias: Chromecast off
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: remote.living_room
      to: 'off'
      for:
        seconds: 30
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.cctv

